import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Reduxprovider from '@/components/redux/features/provider';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'phone hunter project ',
  description: 'Generated by create next app description',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="../app/favicon.ico" sizes="any" /> */}
      </head>
      <body className={inter.className}>
        <Reduxprovider>{children}</Reduxprovider>
      </body>
    </html>
  );
}

